version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/FsCheckCSharp"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: FSharp.Core
    versions:
    - 5.0.0
