version: 1.0.{build}
branches:
  only:
  - master
image: Ubuntu1804
configuration: Release
build:
  project: src/FsCheckCSharp/FsCheckCSharp.csproj
  verbosity: minimal
artifacts:
- path: src/FsCheckCSharp/bin/Release/*.nupkg
- path: src/FsCheckCSharp/bin/Release/*.snupkg
deploy:
- provider: NuGet
  api_key:
    secure: hbDqibGxfpPIaFVOiZOprzr5Kvrui9Pmq0I3XkncYTew4aruZAVUKTbA+Ch1mfLP
  skip_symbols: true
  on:
    branch: master